name: Flutter Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        # We use 'find' to run pub get wherever the pubspec.yaml is
        run: |
          cd $(find . -name pubspec.yaml -exec dirname {} \;)
          flutter pub get

      - name: Build APK
        # This finds the folder with the android directory and builds from there
        run: |
          PROJECT_DIR=$(find . -name android -exec dirname {} \;)
          cd $PROJECT_DIR
          flutter build apk --release --no-tree-shake-icons --no-shrink--dart-define=STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: "**/*.apk"